poke-api-uri: https://pokeapi.co/api/v2/pokemon
server:
  port: 8081
  servlet:
    context-path: /api/v2

spring:
  data:
    mongodb:
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin
      host: spring-data-mongo-db
      port: 27017
      database: pokedex_db
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER