poke-api-uri: https://pokeapi.co/api/v2/pokemon
server:
  port: 8081
  servlet:
    context-path: /api/v1
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pokedex_db
spring:
  data:
    mongodb:
      password: root
      username: root
      authentication-database: admin